import React, { createContext, useState, useContext, useEffect } from 'react';

export const translations = {
  en: {
    // ⬇️ GENERAL TERMINOLOGY
    app_name: "Sanatani Bandhan",
    portal_subtitle: "Universal Community Portal",
    workspace: "Workspace",
    status: "Status", 
    nav_home: "Command Center",
    nav_directory: "Member Directory",
    nav_guests: "Guest CRM",
    nav_treasury: "Treasury & Ledger",
    nav_prachar: "Broadcast Desk",
    nav_panjika: "Events & Calendar",
    nav_polls: "Community Voting",
    nav_marketing: "Social Assistant",
    nav_settings: "Workspace Settings",
    nav_assets: "Assets & Records", 
    nav_inventory: "Store & Inventory", 
    members: "Members",
    funds: "Funds",

    // ✨ NEW NAVIGATION GROUP & MODULE KEYS
    nav_group_core: "Core Workspace",
    nav_group_community: "Community & CRM",
    nav_group_finance: "Finance & Events",
    nav_group_settings: "Outreach & Settings",
    nav_group_logistics: "Rituals & Logistics",
    nav_vivah: "Vivah Matrimonial",
    nav_vanshavali: "Lineage Registry",
    nav_shradh: "Pitru Shradh",
    community_feed: "Darshan & Feed",
    my_ritual_diary: "My Ritual Diary",

    // ⬇️ LOGIN & REGISTRATION
    login_secure: "Secure Login",
    login_create: "Create Workspace",
    login_admin: "Admin",
    login_devotee: "Devotee",
    login_email: "Admin Email Address",
    login_pass: "Master Password",
    login_wid: "Workspace ID or Email",
    login_identity: "Your ID, Phone, or Email",
    login_pin: "Secure PIN",
    btn_access_portal: "Secure Access",
    login_forgot: "Forgot Password / PIN?",
    reg_warning_title: "Wait! Are you a Devotee?",
    reg_warning_desc_1: "If your ",
    reg_warning_desc_2: " already uses this app, do not create a workspace. Ask your Admin for your Login ID.",
    reg_step1: "Step 1: Workspace Info",
    reg_org_type: "Organization Type",
    reg_org_name: "Name",
    reg_address: "Full Address (Optional)",
    reg_desc: "Short Description (Optional)",
    reg_step2: "Step 2: Admin Profile",
    reg_your_name: "Your Name *",
    reg_your_phone: "Your Phone *",
    reg_official_email: "Official Email *",
    btn_create_dynamic: "Create Secure {X}",
    head_admin: "Head Admin",

    // ⬇️ LANDING PAGE & FOOTER 
    hero_badge: "The Ultimate Command Center for Hindu Communities",
    hero_title_1: "From Paper Registers to a",
    hero_title_2: "Digital Workspace.",
    hero_subtitle: "Unite your Ashram, Sangha, or Mandir. Stop losing records and fighting over funds. Manage lifelong devotees, track Chanda securely, and broadcast Utsav alerts—all from one secure dashboard.",
    btn_create_free: "Create Free Account",
    btn_watch_demo: "Watch System Demo",
    btn_login: "Login",
    btn_establish: "Establish Workspace",
    nav_features: "Features",
    nav_pricing: "Pricing",
    nav_security: "Security",
    trust_banner: "Empowering The Global Sanatani Family",
    features_title: "Four Pillars of Digital Management",
    features_subtitle: "Solving the biggest headaches for committee members.",
    footer_privacy: "Privacy Policy",
    footer_terms: "Terms of Service",
    footer_contact: "Contact Support",

    // ✨ Enterprise Capabilities Showcase Keys 
    enterprise_badge: "Enterprise-Grade Infrastructure",
    enterprise_title: "Next-Generation Technology for Modern Communities",
    feat_apk_title: "Android APK & OTA Sync",
    feat_apk_desc: "Native offline app support with Capgo Over-The-Air silent updates.",
    feat_memo_title: "Zero-Cost Memos",
    feat_memo_desc: "Client-side deep image compression saving cloud storage and bandwidth.",
    feat_qr_title: "Smart QR Auto-Login",
    feat_qr_desc: "Generated PDF credentials embedded with secure login deep links.",
    feat_support_title: "Secure Live Support",
    feat_support_desc: "Enterprise Tawk.to widget integrated with HMAC Secure Mode identification.",

    // ⬇️ LEAD GEN & CONTACT 
    contact_title: "Contact Support & Sales",
    contact_wa: "Direct WhatsApp Line",
    contact_wa_desc: "Get instant support or onboarding help directly from our core team.",
    contact_wa_btn: "Message on WhatsApp",
    contact_name: "Your Full Name",
    contact_info: "Email or Phone Number",
    contact_msg: "How can we help you grow?",
    contact_send: "Send Message",

    // Carousel Features 
    feat_1_title: "Stop Losing Paper Registers",
    feat_1_pain: "Are physical record books tearing, getting lost, or taking hours to search through?",
    feat_1_sol: "Digitally manage thousands of profiles, track Gotras, and instantly find contact details in seconds with our encrypted CRM.",
    feat_2_title: "End Financial Disputes",
    feat_2_pain: "Facing trust issues, missing receipts, or manual calculation errors with collected funds?",
    feat_2_sol: "Achieve 100% financial transparency. Track lifetime contributions securely and generate instant PDF audit reports.",
    feat_3_title: "Never Call 500 People Again",
    feat_3_pain: "Calling hundreds of members individually to invite them to an event or remind them of dues is exhausting.",
    feat_3_sol: "Reach your entire community instantly. Send automated mass SMS or WhatsApp alerts for events with a single click.",
    feat_4_title: "Resolve Committee Chaos",
    feat_4_pain: "Are committee decisions causing endless arguments, bias, and a lack of consensus?",
    feat_4_sol: "Launch secure, encrypted digital polls for community voting. Our mathematically secure engine guarantees fair decision-making.",

    // Pricing 
    pricing_title: "Transparent Pricing for Sanatanis",
    pricing_subtitle: "Start for free. Upgrade when your community grows.",
    pricing_forever: "Forever",
    pricing_per_year: "/ Year",
    btn_start_free: "Start Free Workspace",
    free_feat_1: "Up to {X} Member Profiles",
    free_feat_2: "Basic Funds Tracking",
    free_feat_3: "Up to {X} Active Polls",
    free_feat_4: "{X} PDF Master Reports / Month",

    // ✨ PROFILE & NOTIFICATIONS
    signed_in_as: "Signed in as",
    my_profile: "My Profile",
    secure_logout: "Secure Logout",
    notifications: "Notifications",
    no_notifications: "You're all caught up!",
    new_request: "New Access Request",
    upcoming_event: "Upcoming Event",
    active_poll: "Active Poll",
    quick_guide_title: "Command Center Guide",

    // ✨ ENTERPRISE DIRECTORY, PROFILE & HUB KEYS 
    req_identity_data: "Required Identity Data",
    ext_details: "Extended Details (Optional)",
    nid: "National ID (NID)",
    father_name: "Father's Name",
    mother_name: "Mother's Name",
    full_address: "Full Physical Address",
    cultural_desig: "Cultural Designation",
    sys_role: "System Access Role",
    prov_profile: "Provision Secure Profile",
    seva_index: "Seva Index",
    seva_desc: "Your current rank is",
    digital_qr: "Digital QR Identity",
    qr_desc: "Generate the secure PDF ID Card or view the live Auto-Login QR Code for instant device authentication.",
    view_qr: "View QR",
    hide_qr: "Hide QR",
    download_pdf_card: "Download PDF",
    scan_auto_login: "Scan to Auto-Login",
    recent_trans: "Recent Transactions",
    pdf_report: "PDF Report",
    msg_whatsapp: "Message on WhatsApp",
    admin_controls: "Critical Controls",
    reset_pin: "Reset Secure PIN",
    demote_member: "Demote to Member",
    promote_manager: "Promote to Manager",
    delete_record: "Permanently Erase Record",
    identity_tab: "Identity",
    activity_tab: "Activity",
    security_tab: "Security",
    gate_pass: "Gate Pass",
    vedic_hub: "Vedic Hub",
    contact_geo: "Contact & Geography",
    blood_group: "Blood Group",
    country: "Country",
    gotra_lineage: "Gotra Lineage",
    not_provided: "Not Provided",

    // ✨ VIVAH & GLOBAL PUROHIT WIDGET KEYS
    vivah_title: "Vivah Bandhan Matrimonial",
    vivah_subtitle: "Find verified, compatible matches within the Sanatan community based on strict Gotra alignment.",
    create_profile: "Create Matrimonial Profile",
    global_purohit_registry: "Global Purohit Registry",
    apply_global_purohit: "Apply as Global Purohit",
    apply_purohit_desc: "Submit your profile for verification to accept ritual bookings globally.",
    btn_submit_kyc: "SUBMIT KYC",
    application_submitted: "Application submitted for verification!",
    global_scholar: "Global Scholar",
    account_recovery_qr: "Account Recovery QR",
    qr_recovery_desc: "Download or scan this to automatically log back into your workspace if you forget your PIN.",
    qr_warning: "WARNING: This QR code contains your secure PIN. Do not show this to volunteers at the gate. Use the 'Gate Pass' tab instead.",

    // ✨ GLOBAL PUROHIT KYC MODAL KEYS
    kyc_form_title: "Global Scholar KYC Application",
    kyc_form_subtitle: "Submit your credentials to join the verified global registry.",
    kyc_specialization: "Primary Specialization",
    kyc_specialization_ph: "e.g., Vivah Sanskar, Vastu Shanti, Astrology",
    kyc_experience: "Years of Experience",
    kyc_lineage: "Gotra & Vedic Lineage",
    kyc_lineage_ph: "e.g., Kashyap Gotra, Rigveda",
    kyc_location: "Current City / Mandir Affiliation",
    kyc_location_ph: "e.g., Kashi Vishwanath, Varanasi",
    kyc_document: "Verification Document (ID/Certificate)",
    btn_submit_application: "Submit KYC Application",

    // ✨ GUEST MANAGER KEYS
    guest_crm_title: "Guest Relations & Event Check-In",
    guest_crm_subtitle: "Cultivate walk-in visitors, manage VIP invitations, and record gate attendance.",
    growth_pipeline: "Growth Pipeline",
    event_roster: "Event Roster & Gate",
    add_new_guest: "Add New Guest",
    search_guest: "Search by name, phone, or admin notes...",
    gate_checkin_mode: "Gate Check-In Mode",
    select_event: "Select an Event",
    switch_event: "Switch Active Event",
    door_roster: "Door Attendance Roster",
    checked_in: "Checked In:",
    no_events_found: "No upcoming events found in Panjika.",
    convert_member: "Convert Member",
    active_member: "Active Member",
    gate_checkin: "Gate Check-In",
    register_guest: "Register New Guest",
    classification: "Classification",
    general_guest: "General Guest",
    vip_dignitary: "VIP Dignitary",
    walk_in_donor: "Walk-In Donor",
    volunteer_prospect: "Volunteer Prospect",
    admin_note: "Admin Reference Note",
    save_pipeline: "SAVE TO PIPELINE",
    promote_devotee: "PROMOTE TO DEVOTEE",
    delete_guest: "DELETE GUEST RECORD",

    // ✨ DEVOTEE GRID: CHANDA, FILTERS, & CSV
    filters: "Filters",
    filter_all: "All Activities",
    filter_income: "Income Only",
    filter_expense: "Expenses Only",
    amount_bdt: "Amount (৳) *",
    payment_method: "Payment Method",
    note_optional: "Note (Optional)",
    handled_by: "Handled By *",
    search_name: "Type name to search...",
    btn_generate_receipt: "Generate Official PDF Receipt",
    no_matching_activities: "No matching activities found.",
    bulk_csv_importer: "Bulk CSV Importer",
    csv_subtitle: "Digitize paper registers instantly.",
    download_template: "Download Template",
    format_data: "Format Your Data",
    upload_file: "Upload File",
    data_validated: "Data Validated",
    records: "Records",
    btn_cancel: "Cancel",
    btn_import: "Import",
    guide_devotee_step1_title: "1. Provision Profiles",
    guide_devotee_step1_desc: "Add devotees to your digital workspace securely. Generate PDF ID cards with auto-login QR codes.",
    guide_devotee_step2_title: "2. Log Chanda",
    guide_devotee_step2_desc: "Record incoming donations directly to a member's profile. Download and share official PDF receipts instantly.",
    guide_devotee_step3_title: "3. Admin Controls",
    guide_devotee_step3_desc: "Assign roles (Manager/Admin), reset secure PINs, or update identity details from the Security tab.",

    // ✨ TREASURY & LEDGER KEYS
    err_only_images: "Only images allowed.",
    error: "Error",
    success: "Success",
    err_unauthorized: "Unauthorized.",
    err_amount_required: "Amount required.",
    err_select_member: "Select a member.",
    err_guest_name_req: "Guest name required.",
    recorded_success: "recorded successfully!",
    err_all_fields_req: "All fields required.",
    no_memo: "No Memo",
    edit_cost: "Edit cost",
    current: "Current",
    enter_new_amt: "Enter New Amount",
    record_updated: "Record updated successfully.",
    pdf_engine_loading: "PDF engine loading...",
    no_data_export: "No data to export.",
    pdf_limit_reached: "Limit reached.",
    date: "Date",
    donor_name: "Name",
    amount: "Amount",
    note: "Note",
    collected_by: "Auth",
    event: "Event",
    item: "Item",
    memo_no: "Memo No",
    logged_by: "Auth",
    unknown_donor: "Unknown",
    unknown_event: "Unknown",
    treasury_title: "Treasury Ledger",
    treasury_subtitle: "Financial Tracking",
    quick_guide: "Quick Guide",
    sort_newest: "Newest",
    sort_oldest: "Oldest",
    sort_high: "Highest Amount",
    sort_low: "Lowest Amount",
    export_csv: "CSV",
    export_pdf: "PDF",
    how_to_use: "How to use the Treasury",
    guide_step1_title: "1. Record Transactions",
    guide_step1_desc: "Use the red/green + Record buttons to log funds or expenses. You can instantly generate PDF receipts for donors.",
    guide_step2_title: "2. Attach Memos Free",
    guide_step2_desc: "When logging expenses, tap the camera icon to snap a photo of physical memos. It saves securely at zero database cost.",
    guide_step3_title: "3. Track & Export",
    guide_step3_desc: "Filter by date, search by name, or sort by amount. Then click Export PDF for official committee audit reports.",
    tab_chanda: "Chanda",
    tab_expenses: "Expenses",
    total_amount: "Total Amount",
    filtered: "Filtered",
    btn_record_chanda: "Record Income",
    btn_record_expense: "Record Expense",
    search_donors: "Search donors...",
    search_events: "Search events...",
    contributions: "Contributions",
    seva_items: "Items",
    general_donation: "General Donation",
    memo: "Memo",
    edit_history: "Edit History",
    view_memo_photo: "View Memo",
    download_receipt: "Download Receipt",
    no_data_found: "No Data Found",
    adjust_filters: "Adjust filters to see results",
    page: "Page",
    registered_devotee: "Member",
    guest_donor: "Guest",
    search_directory: "Search Directory",
    type_to_search: "Type to search...",
    guest_name: "Guest Name",
    guest_phone: "Guest Phone",
    optional: "Optional",
    cash: "CASH",
    bank_transfer: "BANK TRANSFER",
    mobile_banking: "MOBILE BANKING",
    btn_confirm_chanda: "Confirm",
    btn_confirm_expense: "Confirm",
    event_name: "Event Name",
    item_purchased: "Item",
    photo_attached: "Photo Attached",
    attach_memo_photo: "Attach Memo Photo",
    change_photo: "Change",
    take_photo_desc: "Click to snap a picture of the physical receipt.",

    // ✨ POOJA & SEVA BOOKING KEYS
    nav_pooja: "Pooja & Seva Booking Desk",
    pooja_desk_desc: "Manage ritual reservations, capture Gotra & Nakshatra Sankalp, and sync temple revenue.",
    active_bookings: "Active Bookings",
    pooja_catalog: "Pooja Catalog",
    book_pooja: "Book New Pooja",
    schedule_pooja: "Schedule Pooja & Seva",
    pooja_satyanarayan: "Satyanarayan Katha & Puja",
    pooja_rudrabhishek: "Rudrabhishek Seva",
    pooja_namakaran: "Namakaran Sanskar",
    pooja_grihapravesh: "Griha Pravesh Puja",
    pooja_archana: "Daily Archana / Pushpanjali",
    search_records: "Search by devotee, pooja, gotra...",
    devotee_name: "Yajamana",
    devotee_full_name: "Devotee Full Name",
    gotra: "Gotra",
    nakshatra: "Nakshatra",
    assigned_purohit: "Assigned Purohit",
    pooja_type: "Select Ritual / Seva",
    yajamana_name: "Yajamana Name",
    essential: "Essential",
    booking_date: "Booking Date",
    dakshina_amount: "Dakshina Amount",
    btn_confirm_booking: "Confirm Booking & Sync Treasury",
    archived: "Archived",
    mark_completed: "Mark Completed",
    cancel: "Cancel",
    book_now: "Book Now",

    // ✨ PROFILE & NOTIFICATIONS ENGINE KEYS
    updates: "Updates",
    activity_center: "Activity Center",
    pending: "Pending",
    no_activities: "No activities found.",
    req_approval: "requests approval:",
    btn_approve: "APPROVE",
    btn_reject: "REJECT",
    performed_action: "performed action:",
    operating_currency: "Operating Currency",
    tap_to_edit: "Tap to Edit",
    full_name: "Full Name",
    phone_number: "Phone Number",
    email: "Email",
    personal_transactions: "Personal Transactions",
    security_controls: "Security Controls",
    btn_save: "Save",
    events_attended: "Events Attended",
    lifetime_donated: "Lifetime Donated",

    // UPGRADE REASONS
    upgrade_title: "Ready to Scale?",
    upgrade_r1: "Unlimited Member Profiles",
    upgrade_r2: "Infinite Master PDF Reports",
    upgrade_r3: "Verified Organization Badge",
    btn_upgrade_pro: "Upgrade to Smart Pro",

    // ✨ MASTER SETTINGS KEYS
    settings_subtitle: "Manage identity, usage counters, and secure access.",
    official_identity: "Official Identity",
    name: "Name",
    org_type: "Organization Type",
    official_phone: "Official Phone",
    official_email: "Official Email",
    physical_address: "Physical Address",
    legal_info: "Legal & Extended Information",
    reg_no: "Registration No.",
    tax_id: "Tax ID (PAN/BIN/EIN)",
    mission_desc: "Mission / Description",
    btn_save_settings: "SAVE SETTINGS",
    admin_security: "Admin Security",
    new_master_pass: "New Master Password",
    min_6_char: "Min 6 characters",
    confirm_pass: "Confirm Password",
    retype_pass: "Retype password",
    btn_update_pass: "UPDATE PASSWORD",
    current_limits: "Current Limits",
    registered_members: "Registered Members",
    pdfs_generated: "PDFs Generated",
    offer_dakshina: "OFFER DAKSHINA (UPGRADE)",
    update_password: "Update Admin Password",
    confirm_pass_update: "Are you sure you want to change your secure master password?",
    pass_updated_success: "Secure Password Updated Successfully!",
    err_no_auth: "No active auth session found. Please re-login.",
    err_recent_login: "Security timeout. Please log out and log back in to change password.",
    err_trx_req: "Contact and Transaction ID are required.",
    req_submitted: "Request Submitted!",
    dakshina_submitted_desc: "✅ Your transaction ID has been securely submitted. Our backend team will verify this within 24 hours and activate your SMART PRO status.",
    understood: "UNDERSTOOD",
    copied_success: "Merchant Number Copied!",
    settings_saved: "Workspace Settings Updated Successfully!",
    err_pass_length: "Password must be at least 6 characters.",
    err_pass_match: "Passwords do not match.",

    // VEDIC SHLOKA DATABASE 
    quotes: [
      { text: "कर्मण्येवाधिकारस्ते मा फलेषु कदाचन।", meaning: "You have a right to perform your prescribed duty, but you are not entitled to the fruits of action.", source: "Bhagavad Gita 2.47" },
      { text: "उद्धरेदात्मनात्मानं नात्मानमवसादयेत्।", meaning: "Elevate yourself through the power of your mind, and not degrade yourself.", source: "Bhagavad Gita 6.5" },
      { text: "सत्यमेव जयते नानृतं", meaning: "Truth alone triumphs; not falsehood.", source: "Mundaka Upanishad 3.1.6" },
      { text: "एकं सद्विप्रा बहुधा वदन्ति", meaning: "Truth is One, the wise call it by many names.", source: "Rig Veda 1.164.46" }
    ],

    // ✨ TYPE OVERRIDES (UNIVERSAL ENTERPRISE MAPPING)
    Mandir: { workspace: "Mandir", nav_directory: "Devotee Directory", nav_panjika: "Utsav & Panjika", nav_prachar: "Dharma Prochar", members: "Bhaktas", funds: "Chanda", nav_assets: "Temple Assets", nav_inventory: "Bhandara & Store" },
    Goshala: { workspace: "Goshala", nav_directory: "Gau Sevak Directory", nav_panjika: "Goshala Events", nav_prachar: "Goshala Broadcast", members: "Gau Sevaks", funds: "Gau Seva Nidhi", nav_assets: "Gomata & Nandi Records", nav_inventory: "Fodder & Medicine" },
    Sangha: { workspace: "Sangha", nav_directory: "Sangha Members", nav_panjika: "Adhiveshan (Meetings)", nav_prachar: "Sangha Broadcast", members: "Sadasya", funds: "Sahayog", nav_assets: "Sangha Assets", nav_inventory: "Store Management" },
    Ashram: { workspace: "Ashram", nav_directory: "Sadhak Directory", nav_panjika: "Ashram Schedule", nav_prachar: "Ashram Broadcast", members: "Sadhaks", funds: "Ashram Nidhi", nav_assets: "Ashram Assets", nav_inventory: "Kitchen & Medicine" },
    Gurukul: { workspace: "Gurukul", nav_directory: "Vidyarthi Directory", nav_panjika: "Academic Calendar", nav_prachar: "Student Alerts", members: "Vidyarthis", funds: "Guru Dakshina", nav_assets: "Campus Assets", nav_inventory: "Library & Supplies" },
    Satsang: { workspace: "Satsang Kendra", nav_directory: "Anuyayi Directory", nav_panjika: "Satsang Schedule", nav_prachar: "Satsang Broadcast", members: "Anuyayis", funds: "Bhent", nav_assets: "Kendra Assets", nav_inventory: "Store Management" },
    Yoga: { workspace: "Yoga Kendra", nav_directory: "Sadhak Directory", nav_panjika: "Class Schedule", nav_prachar: "Wellness Broadcast", members: "Sadhaks", funds: "Yoga Nidhi", nav_assets: "Equipment Records", nav_inventory: "Inventory" },
    Trust: { workspace: "Seva Trust", nav_directory: "Sevadar Directory", nav_panjika: "Activity Calendar", nav_prachar: "Trust Broadcast", members: "Sevadars", funds: "Seva Nidhi", nav_assets: "Trust Assets", nav_inventory: "Relief & Medical Store" }
  },

  bn: {
    app_name: "সনাতনী বন্ধন",
    portal_subtitle: "সার্বজনীন কমিউনিটি পোর্টাল",
    workspace: "ওয়ার্কস্পেস",
    status: "স্ট্যাটাস", 
    nav_home: "কমান্ড সেন্টার",
    nav_directory: "সদস্য ডিরেক্টরি",
    nav_guests: "গেস্ট সিআরএম",
    nav_treasury: "কোষাগার ও হিসাব",
    nav_prachar: "ব্রডকাস্ট ডেস্ক",
    nav_panjika: "ইভেন্ট ও ক্যালেন্ডার",
    nav_polls: "ভোটিং সিস্টেম",
    nav_marketing: "সোশ্যাল অ্যাসিস্ট্যান্ট",
    nav_settings: "সেটিংস",
    nav_assets: "সম্পদ ও রেকর্ড",
    nav_inventory: "স্টোর ও ইনভেন্টরি",
    members: "সদস্যবৃন্দ",
    funds: "তহবিল",

    // ✨ BENGALI TRANSLATIONS FOR NEW NAVIGATION KEYS
    nav_group_core: "মূল ওয়ার্কস্পেস",
    nav_group_community: "কমিউনিটি ও সিআরএম",
    nav_group_finance: "অর্থ ও ইভেন্ট",
    nav_group_settings: "প্রচার ও সেটিংস",
    nav_group_logistics: "পূজা ও লজিস্টিকস",
    nav_vivah: "বিবাহ বন্ধন ম্যাট্রিমোনিয়াল",
    nav_vanshavali: "বংশাবলী রেজিস্ট্রি",
    nav_shradh: "পিতৃশ্রাদ্ধ ডেস্ক",
    community_feed: "দর্শন ও ফিড",
    my_ritual_diary: "আমার রিচুয়াল ডায়েরি",

    login_secure: "নিরাপদ লগইন",
    login_create: "ওয়ার্কস্পেস তৈরি করুন",
    login_admin: "অ্যাডমিন",
    login_devotee: "ভক্ত / সদস্য",
    login_email: "অ্যাডমিন ইমেইল",
    login_pass: "মাস্টার পাসওয়ার্ড",
    login_wid: "ওয়ার্কস্পেস আইডি বা ইমেইল",
    login_identity: "আপনার আইডি, ফোন, বা ইমেইল",
    login_pin: "নিরাপদ পিন (PIN)",
    btn_access_portal: "নিরাপদ প্রবেশ",
    login_forgot: "পাসওয়ার্ড / পিন ভুলে গেছেন?",
    reg_warning_title: "অপেক্ষা করুন! আপনি কি সাধারণ সদস্য?",
    reg_warning_desc_1: "আপনার ",
    reg_warning_desc_2: " যদি ইতিমধ্যে এই অ্যাপটি ব্যবহার করে, তবে নতুন ওয়ার্কস্পেস তৈরি করবেন না। লগইন করার জন্য অ্যাডমিনের কাছ থেকে আইডি সংগ্রহ করুন।",
    reg_step1: "ধাপ ১: প্রতিষ্ঠানের তথ্য",
    reg_org_type: "প্রতিষ্ঠানের ধরন",
    reg_org_name: "নাম",
    reg_address: "সম্পূর্ণ ঠিকানা (ঐচ্ছিক)",
    reg_desc: "সংক্ষিপ্ত বিবরণ (ঐচ্ছিক)",
    reg_step2: "ধাপ ২: অ্যাডমিন প্রোফাইল",
    reg_your_name: "আপনার নাম *",
    reg_your_phone: "আপনার ফোন *",
    reg_official_email: "অফিসিয়াল ইমেইল *",
    btn_create_dynamic: "নিরাপদ {X} তৈরি করুন",
    head_admin: "প্রধান অ্যাডমিন",

    hero_badge: "হিন্দু সম্প্রদায়ের জন্য চূড়ান্ত কমান্ড সেন্টার",
    hero_title_1: "কাগজের খাতা থেকে",
    hero_title_2: "ডিজিটাল ওয়ার্কস্পেস।",
    hero_subtitle: "আপনার আশ্রম, সংঘ বা মন্দিরকে একত্রিত করুন। খাতা হারানো এবং তহবিলের হিসাব নিয়ে বিবাদ বন্ধ করুন। আজীবন প্রোফাইল পরিচালনা করুন, নিরাপদে সংগ্রহ ট্র্যাক করুন এবং অ্যালার্ট দিন—সবকিছু একটি নিরাপদ ড্যাশবোর্ড থেকে।",
    btn_create_free: "ফ্রি অ্যাকাউন্ট খুলুন",
    btn_watch_demo: "সিস্টেম ডেমো দেখুন",
    btn_login: "লগইন",
    btn_establish: "ওয়ার্কস্পেস তৈরি করুন",
    nav_features: "ফিচারসমূহ",
    nav_pricing: "প্যাকেজ মূল্য",
    nav_security: "নিরাপত্তা",
    trust_banner: "বিশ্বব্যাপী সনাতনী পরিবারকে ক্ষমতায়ন করা হচ্ছে",
    features_title: "ডিজিটাল ব্যবস্থাপনার চার মূলভিত্তি",
    features_subtitle: "কমিটি সদস্যদের সবচেয়ে বড় সমস্যাগুলোর স্মার্ট সমাধান।",
    footer_privacy: "গোপনীয়তা নীতি",
    footer_terms: "ব্যবহারের শর্তাবলী",
    footer_contact: "যোগাযোগ করুন",

    enterprise_badge: "এন্টারপ্রাইজ-গ্রেড ইনফ্রাস্ট্রাকচার",
    enterprise_title: "আধুনিক সম্প্রদায়ের জন্য নেক্সট-জেনারেশন প্রযুক্তি",
    feat_apk_title: "অ্যান্ড্রয়েড এপিকে ও ওটিএ সিঙ্ক",
    feat_apk_desc: "ওভার-দ্যা-এয়ার সাইলেন্ট আপডেটের সাথে নেটিভ অফলাইন অ্যাপ সাপোর্ট।",
    feat_memo_title: "জিরো-কস্ট মেমো স্ক্যান",
    feat_memo_desc: "ক্লায়েন্ট-সাইড ডিপ ইমেজ কম্প্রেশন যা ক্লাউড স্টোরেজ এবং ব্যান্ডউইথ সাশ্রয় করে।",
    feat_qr_title: "স্মার্ট কিউআর অটো-লॉगইন",
    feat_qr_desc: "নিরাপদ লগইন ডিপ লিঙ্ক সহ জেনারেটেড পিডিএফ ক্রেডেনশিয়াল।",
    feat_support_title: "নিরাপদ লাইভ সাপোর্ট",
    feat_support_desc: "এইচএমএসি সিকিউর মোড আইডেন্টিফিকেশন সহ এন্টারপ্রাইজ টক.টু উইজেট।",

    contact_title: "সাপোর্ট এবং সেলস",
    contact_wa: "সরাসরি হোয়াটসঅ্যাপ",
    contact_wa_desc: "আমাদের কোর টিমের কাছ থেকে সরাসরি তাত্ক্ষণিক সহায়তা নিন।",
    contact_wa_btn: "হোয়াটসঅ্যাপে মেসেজ দিন",
    contact_name: "আপনার সম্পূর্ণ নাম",
    contact_info: "ইমেইল বা ফোন নম্বর",
    contact_msg: "আমরা আপনাকে কীভাবে সাহায্য করতে পারি?",
    contact_send: "মেসেজ পাঠান",

    feat_1_title: "কাগজের খাতা হারানোর দিন শেষ",
    feat_1_pain: "আপনার কি কাগজের খাতা ছিঁড়ে যাচ্ছে, হারিয়ে যাচ্ছে, বা তথ্য খুঁজতে ঘণ্টার পর ঘণ্টা সময় লাগছে?",
    feat_1_sol: "হাজার হাজার প্রোফাইল ডিজিটালভাবে পরিচালনা করুন, গোত্র ট্র্যাক করুন এবং আমাদের এনক্রিপ্টেড CRM দিয়ে কয়েক সেকেন্ডের মধ্যে যোগাযোগের বিশদ খুঁজুন।",
    feat_2_title: "আর্থিক হিসাবের স্বচ্ছতা",
    feat_2_pain: "তহবিল সংগ্রহ নিয়ে কি বিশ্বাসহীনতা বা ম্যান्युअल গণনায় ভুল হচ্ছে?",
    feat_2_sol: "১০০% আর্থিক স্বচ্ছতা অর্জন করুন। আজীবন অবদান নিরাপদে ট্র্যাক করুন এবং তাত্ক্ষণিক পিডিএফ অডিট রিপোর্ট তৈরি করুন।",
    feat_3_title: "সবাইকে একসাথে মেসেজ দিন",
    feat_3_pain: "কোনো অনুষ্ঠানে আমন্ত্রণ জানাতে বা বকেয়া মনে করিয়ে দিতে শত শত সদস্যকে আলাদাভাবে কল করা ক্লান্তিকর।",
    feat_3_sol: "এক ক্লিকেই আপনার সমগ্র সম্প্রদায়ের কাছে পৌঁছান। ইভেন্টের জন্য স্বয়ংক্রিয় মাস এসএমএস বা হোয়াটসঅ্যাপ অ্যালার্ট পাঠান।",
    feat_4_title: "কমিটির সিদ্ধান্ত গ্রহণ সহজ করুন",
    feat_4_pain: "কমিটির সিদ্ধান্তগুলো কি অবিরাম তর্ক এবং মতামতের অভাব সৃষ্টি করছে?",
    feat_4_sol: "কমিউনিটি ভোটিংয়ের জন্য সুরক্ষিত, এনক্রিপ্টেড ডিজিটাল পোল চালু করুন। আমাদের প্রযুক্তি সুষ্ঠু সিদ্ধান্ত গ্রহণের নিশ্চয়তা দেয়।",

    pricing_title: "সনাতনীদের জন্য স্বচ্ছ মূল্য নির্ধারণ",
    pricing_subtitle: "বিনামূল্যে শুরু করুন। আপনার সম্প্রদায় বড় হলে আপগ্রেড করুন।",
    pricing_forever: "আজীবন",
    pricing_per_year: "/ বছর",
    btn_start_free: "ফ্রি ওয়ার্কস্পেস শুরু করুন",
    free_feat_1: "সর্বোচ্চ {X} সদস্য প্রোফাইল",
    free_feat_2: "সাধারণ তহবিল ট্র্যাকিং",
    free_feat_3: "সর্বোচ্চ {X} টি সক্রিয় পোল",
    free_feat_4: "মাসে {X} টি পিডিএফ রিপোর্ট",

    signed_in_as: "লগইন করেছেন",
    my_profile: "আমার প্রোফাইল",
    secure_logout: "নিরাপদ লগআউট",
    notifications: "বিজ্ঞপ্তি",
    no_notifications: "কোনো নতুন বিজ্ঞপ্তি নেই!",
    new_request: "নতুন অ্যাক্সেস রিকোয়েস্ট",
    upcoming_event: "আসন্ন ইভেন্ট",
    active_poll: "সক্রিয় পোল",
    quick_guide_title: "কমান্ড সেন্টার গাইড",

    req_identity_data: "প্রয়োজনীয় পরিচয় তথ্য",
    ext_details: "অতিরিক্ত তথ্য (ঐচ্ছিক)",
    nid: "জাতীয় পরিচয়পত্র (NID)",
    father_name: "পিতার নাম",
    mother_name: "মাতার নাম",
    full_address: "সম্পূর্ণ ঠিকানা",
    cultural_desig: "সাংস্কৃতিক পদবী",
    sys_role: "সিস্টেম অ্যাক্সেস রোল",
    prov_profile: "নিরাপদ প্রোফাইল তৈরি করুন",
    seva_index: "সেবা ইনডেক্স",
    seva_desc: "আপনার বর্তমান র‍্যাঙ্ক হলো",
    digital_qr: "ডিজিটাল কিউআর (QR) পরিচয়",
    qr_desc: "ডিভাইস প্রমাণীকরণের জন্য নিরাপদ পিডিএফ আইডি কার্ড তৈরি করুন বা লাইভ অটো-লগইন কিউআর কোড দেখুন।",
    view_qr: "লাইভ কিউআর দেখুন",
    hide_qr: "কিউআর লুকান",
    download_pdf_card: "পিডিএফ কার্ড ডাউনলোড করুন",
    scan_auto_login: "অটো-লগইন স্ক্যান করুন",
    recent_trans: "সাম্প্রতিক লেনদেন",
    pdf_report: "পিডিএফ রিপোর্ট",
    msg_whatsapp: "হোয়াটসঅ্যাপে মেসেজ দিন",
    admin_controls: "অ্যাডমিন কন্ট্রোল",
    reset_pin: "নিরাপদ পিন রিসেট করুন",
    demote_member: "সদস্য হিসেবে ডিমোট করুন",
    promote_manager: "ম্যানেজার হিসেবে প্রমোট করুন",
    delete_record: "রেকর্ড স্থায়ীভাবে মুছুন",
    identity_tab: "পরিচয়",
    activity_tab: "অ্যাক্টিভিটি",
    security_tab: "নিরাপত্তা",
    gate_pass: "গেট পাস",
    vedic_hub: "বেদিক হাব",
    contact_geo: "যোগাযোগ ও ঠিকানা",
    blood_group: "রক্তের গ্রুপ",
    country: "দেশ",
    gotra_lineage: "গোত্র / বংশ",
    not_provided: "দেওয়া হয়নি",

    // ✨ VIVAH & GLOBAL PUROHIT WIDGET KEYS
    vivah_title: "বিবাহ বন্ধন ম্যাট্রিমোনিয়াল",
    vivah_subtitle: "গোত্র এবং সনাতন মূল্যবোধের উপর ভিত্তি করে সঠিক পাত্র-পাত্রী খুঁজুন।",
    create_profile: "প্রোফাইল তৈরি করুন",
    global_purohit_registry: "গ্লোবাল পুরোহিত রেজিস্ট্রি",
    apply_global_purohit: "গ্লোবাল পুরোহিত হিসেবে আবেদন করুন",
    apply_purohit_desc: "সার্বজনীন বুকিংয়ের জন্য আপনার প্রোফাইল জমা দিন।",
    btn_submit_kyc: "কেওয়াইসি জমা দিন",
    application_submitted: "আবেদন যাচাইয়ের জন্য জমা দেওয়া হয়েছে!",
    global_scholar: "গ্লোবাল স্কলার",
    account_recovery_qr: "অ্যাকাউন্ট রিকভারি QR",
    qr_recovery_desc: "আপনার পিন ভুলে গেলে স্বয়ংক্রিয়ভাবে লগ ইন করতে এটি ডাউনলোড বা স্ক্যান করুন।",
    qr_warning: "সতর্কতা: এই QR কোডে আপনার পিন রয়েছে। এটি গেটে স্বেচ্ছাসেবকদের দেখাবেন না। এর বদলে 'গেট পাস' ব্যবহার করুন।",

    // ✨ GLOBAL PUROHIT KYC MODAL KEYS (BENGALI)
    kyc_form_title: "গ্লোবাল স্কলার কেওয়াইসি (KYC) আবেদন",
    kyc_form_subtitle: "ভেরিফাইড গ্লোবাল রেজিস্ট্রিতে যুক্ত হতে আপনার তথ্য জমা দিন।",
    kyc_specialization: "প্রধান দক্ষতা / স্পেশালাইজেশন",
    kyc_specialization_ph: "যেমন: বিবাহ সংস্কার, বাস্তু শান্তি, জ্যোতিষশাস্ত্র",
    kyc_experience: "অভিজ্ঞতার বছর",
    kyc_lineage: "গোত্র ও বেদিক বংশ",
    kyc_lineage_ph: "যেমন: কাশ্যপ গোত্র, ঋগ্বেদ",
    kyc_location: "বর্তমান শহর / মন্দির",
    kyc_location_ph: "যেমন: শ্রী শ্রী লোকনাথ আশ্রম, ঢাকা",
    kyc_document: "যাচাইকরণ নথি (ID/সার্টিফিকেট)",
    btn_submit_application: "কেওয়াইসি আবেদন জমা দিন",

    // ✨ GUEST MANAGER KEYS (BENGALI)
    guest_crm_title: "গেস্ট রিলেশনস ও ইভেন্ট চেক-ইন",
    guest_crm_subtitle: "নতুন দর্শনার্থীদের সদস্য করুন, ভিআইপি আমন্ত্রণ পরিচালনা করুন এবং গেটে উপস্থিতি রেকর্ড করুন।",
    growth_pipeline: "গ্রোথ পাইপলাইন",
    event_roster: "ইভেন্ট রোস্টার ও গেট",
    add_new_guest: "নতুন গেস্ট যোগ করুন",
    search_guest: "নাম, ফোন, বা অ্যাডমিন নোট দিয়ে খুঁজুন...",
    gate_checkin_mode: "গেট চেক-ইন মোড",
    select_event: "একটি ইভেন্ট নির্বাচন করুন",
    switch_event: "ইভেন্ট পরিবর্তন করুন",
    door_roster: "উপস্থিতি রোস্টার (ডোর)",
    checked_in: "চেক-ইন হয়েছে:",
    no_events_found: "পঞ্জিকায় কোনো আসন্ন ইভেন্ট পাওয়া যায়নি।",
    convert_member: "সদস্য করুন",
    active_member: "সক্রিয় সদস্য",
    gate_checkin: "গেট চেক-ইন",
    register_guest: "নতুন গেস্ট নিবন্ধন করুন",
    classification: "শ্রেণীবিভাগ",
    general_guest: "সাধারণ গেস্ট",
    vip_dignitary: "ভিআইপি অতিথি",
    walk_in_donor: "ওয়াক-ইন দাতা",
    volunteer_prospect: "স্বেচ্ছাসেবক সম্ভাবনা",
    admin_note: "অ্যাডমিন রেফারেন্স নোট",
    save_pipeline: "পাইপলাইনে সেভ করুন",
    promote_devotee: "সদস্য হিসেবে প্রমোট করুন",
    delete_guest: "গেস্ট রেকর্ড মুছুন",

    // ✨ DEVOTEE GRID: CHANDA, FILTERS, & CSV (BENGALI)
    filters: "ফিল্টার করুন",
    filter_all: "সকল লেনদেন",
    filter_income: "শুধুমাত্র আয়",
    filter_expense: "শুধুমাত্র ব্যয়",
    amount_bdt: "পরিমাণ (৳) *",
    payment_method: "পেমেন্ট মাধ্যম",
    note_optional: "বিবরণ (ঐচ্ছিক)",
    handled_by: "সংগ্রহকারী *",
    search_name: "নাম লিখে খুঁজুন...",
    btn_generate_receipt: "অফিসিয়াল পিডিএফ রসিদ তৈরি করুন",
    no_matching_activities: "কোনো লেনদেন পাওয়া যায়নি।",
    bulk_csv_importer: "বাল্ক CSV ইম্পোর্টার",
    csv_subtitle: "কাগজের খাতা নিমিষেই ডিজিটাল করুন।",
    download_template: "টেমপ্লেট ডাউনলোড করুন",
    format_data: "ডেটা ফরম্যাট করুন",
    upload_file: "ফাইল আপলোড করুন",
    data_validated: "ডেটা যাচাই সম্পন্ন",
    records: "টি প্রোফাইল",
    btn_cancel: "বাতিল",
    btn_import: "ইমপোর্ট করুন",
    guide_devotee_step1_title: "১. প্রোফাইল তৈরি করুন",
    guide_devotee_step1_desc: "আপনার ডিজিটাল ওয়ার্কস্পেসে সদস্যদের যুক্ত করুন। অটো-লগইন কিউআর কোডসহ পিডিএফ আইডি কার্ড তৈরি করুন।",
    guide_devotee_step2_title: "২. তহবিল সংগ্রহ",
    guide_devotee_step2_desc: "সরাসরি একজন সদস্যের প্রোফাইলে চাঁদা বা দান লগ করুন এবং সাথে সাথে পিডিএফ রসিদ শেয়ার করুন।",
    guide_devotee_step3_title: "৩. অ্যাডমিন কন্ট্রোল",
    guide_devotee_step3_desc: "ম্যানেজার/অ্যাডমিন রোল সেট করুন, পিন রিসেট করুন, বা নিরাপত্তা ট্যাব থেকে পরিচয় তথ্য আপডেট করুন।",

    // ✨ TREASURY & LEDGER KEYS (BENGALI)
    err_only_images: "শুধুমাত্র ছবি অনুমোদিত।",
    error: "ত্রুটি",
    success: "সফল",
    err_unauthorized: "অননুমোদিত অ্যাক্সেস।",
    err_amount_required: "পরিমাণ আবশ্যক।",
    err_select_member: "একজন সদস্য নির্বাচন করুন।",
    err_guest_name_req: "গেস্টের নাম আবশ্যক।",
    recorded_success: "সফলভাবে রেকর্ড করা হয়েছে!",
    err_all_fields_req: "সব ফিল্ড পূরণ করা আবশ্যক।",
    no_memo: "কোনো মেমো নেই",
    edit_cost: "খরচ এডিট করুন",
    current: "বর্তমান",
    enter_new_amt: "নতুন পরিমাণ লিখুন",
    record_updated: "সফলভাবে আপডেট করা হয়েছে।",
    pdf_engine_loading: "পিডিএফ ইঞ্জিন লোড হচ্ছে...",
    no_data_export: "এক্সপোর্ট করার মতো কোনো ডেটা নেই।",
    pdf_limit_reached: "লিমিট শেষ।",
    date: "তারিখ",
    donor_name: "নাম",
    amount: "পরিমাণ",
    note: "বিবরণ",
    collected_by: "সংগ্রহকারী",
    event: "ইভেন্ট",
    item: "খাত",
    memo_no: "মেমো নং",
    logged_by: "রেকর্ডকারী",
    unknown_donor: "অজানা",
    unknown_event: "অজানা",
    treasury_title: "ট্রেজারি লেজার",
    treasury_subtitle: "আর্থিক ট্র্যাকিং",
    quick_guide: "কুইক গাইড",
    sort_newest: "নতুন আগে",
    sort_oldest: "পুরোনো আগে",
    sort_high: "সর্বোচ্চ পরিমাণ",
    sort_low: "সর্বনিম্ন পরিমাণ",
    export_csv: "CSV",
    export_pdf: "PDF",
    how_to_use: "ট্রেজারি কীভাবে ব্যবহার করবেন",
    guide_step1_title: "১. লেনদেন রেকর্ড করুন",
    guide_step1_desc: "আয় বা ব্যয় রেকর্ড করতে লাল/সবুজ + বোতাম ব্যবহার করুন। আপনি তাত্ক্ষণিকভাবে দাতাদের জন্য পিডিএফ রসিদ তৈরি করতে পারেন।",
    guide_step2_title: "২. মেমো সংযুক্ত করুন",
    guide_step2_desc: "ব্যয় রেকর্ড করার সময়, ফিজিক্যাল মেমোর ছবি তুলতে ক্যামেরা আইকনে ট্যাপ করুন। এটি ডেটাবেস খরচ ছাড়াই নিরাপদে সংরক্ষিত হয়।",
    guide_step3_title: "৩. ট্র্যাক এবং এক্সপোর্ট করুন",
    guide_step3_desc: "তারিখ, নাম, বা পরিমাণ অনুযায়ী ফিল্টার করুন। এরপর অফিশিয়াল অডিট রিপোর্টের জন্য Export PDF এ ক্লিক করুন।",
    tab_chanda: "তহবিল সংগ্রহ",
    tab_expenses: "ব্যয়",
    total_amount: "মোট পরিমাণ",
    filtered: "ফিল্টার করা",
    btn_record_chanda: "আয় রেকর্ড করুন",
    btn_record_expense: "ব্যয় রেকর্ড করুন",
    search_donors: "দাতাদের খুঁজুন...",
    search_events: "ইভেন্ট খুঁজুন...",
    contributions: "অবদান",
    seva_items: "আইটেম",
    general_donation: "সাধারণ অনুদান",
    memo: "মেমো",
    edit_history: "এডিট হিস্ট্রি",
    view_memo_photo: "মেমো দেখুন",
    download_receipt: "রসিদ ডাউনলোড করুন",
    no_data_found: "কোনো ডেটা পাওয়া যায়নি",
    adjust_filters: "ফলাফল দেখতে ফিল্টার পরিবর্তন করুন",
    page: "পৃষ্ঠা",
    registered_devotee: "সদস্য",
    guest_donor: "গেস্ট",
    search_directory: "ডিরেক্টরি খুঁজুন",
    type_to_search: "খুঁজতে টাইপ করুন...",
    guest_name: "গেস্টের নাম",
    guest_phone: "গেস্টের ফোন",
    optional: "ঐচ্ছিক",
    cash: "নগদ",
    bank_transfer: "ব্যাংক ট্রান্সফার",
    mobile_banking: "মোবাইল ব্যাংকিং",
    btn_confirm_chanda: "নিশ্চিত করুন",
    btn_confirm_expense: "নিশ্চিত করুন",
    event_name: "ইভেন্টের নাম",
    item_purchased: "আইটেম/খাত",
    photo_attached: "ছবি সংযুক্ত",
    attach_memo_photo: "মেমোর ছবি যুক্ত করুন",
    change_photo: "পরিবর্তন",
    take_photo_desc: "ফিজিক্যাল রসিদের ছবি তুলতে ক্লিক করুন।",

    // ✨ POOJA & SEVA BOOKING KEYS (BENGALI)
    nav_pooja: "পূজা ও সেবা ডেস্ক",
    pooja_desk_desc: "পূজা ও সেবার বুকিং পরিচালনা করুন এবং মন্দিরের আয় সিঙ্ক করুন।",
    active_bookings: "সক্রিয় বুকিং",
    pooja_catalog: "পূজা ক্যাটালগ",
    book_pooja: "নতুন পূজা বুকিং",
    schedule_pooja: "পূজা ও সেবা নির্ধারণ করুন",
    pooja_satyanarayan: "সত্যনারায়ণ কথা ও পূজা",
    pooja_rudrabhishek: "রুদ্রাভিষেক সেবা",
    pooja_namakaran: "নামকরণ সংস্কার",
    pooja_grihapravesh: "গৃহপ্রবেশ পূজা",
    pooja_archana: "দৈনিক অর্চনা / পুষ্পাঞ্জলি",
    search_records: "ভক্ত, পূজা, বা গোত্র দিয়ে খুঁজুন...",
    devotee_name: "যজমান / ভক্ত",
    devotee_full_name: "ভক্তের সম্পূর্ণ নাম",
    gotra: "গোত্র",
    nakshatra: "নক্ষত্র",
    assigned_purohit: "নির্ধারিত পুরোহিত",
    pooja_type: "আচার / সেবা নির্বাচন করুন",
    yajamana_name: "যজমানের নাম",
    essential: "আবশ্যক",
    booking_date: "বুকিংয়ের তারিখ",
    dakshina_amount: "দক্ষিণা পরিমাণ",
    btn_confirm_booking: "বুকিং নিশ্চিত করুন ও ট্রেজারিতে সিঙ্ক করুন",
    archived: "আর্কাইভ",
    mark_completed: "সম্পন্ন",
    cancel: "বাতিল",
    book_now: "বুক করুন",

    // ✨ PROFILE & NOTIFICATIONS ENGINE KEYS (BENGALI)
    updates: "আপডেট",
    activity_center: "অ্যাক্টিভিটি সেন্টার",
    pending: "অপেক্ষমান",
    no_activities: "কোনো নতুন অ্যাক্টিভিটি নেই।",
    req_approval: "অনুমোদন চেয়েছেন:",
    btn_approve: "অনুমোদন করুন",
    btn_reject: "বাতিল করুন",
    performed_action: "কাজটি করেছেন:",
    operating_currency: "অপারেটিং মুদ্রা",
    tap_to_edit: "এডিট করতে ট্যাপ করুন",
    full_name: "পুরো নাম",
    phone_number: "ফোন নম্বর",
    email: "ইমেইল",
    personal_transactions: "ব্যক্তিগত লেনদেন",
    security_controls: "নিরাপত্তা কন্ট্রোল",
    btn_save: "সেভ করুন",
    events_attended: "ইভেন্টে অংশগ্রহণ করেছেন",
    lifetime_donated: "মোট অনুদান",

    upgrade_title: "স্কেল করতে প্রস্তুত?",
    upgrade_r1: "আনলিমিটেড সদস্য প্রোফাইল",
    upgrade_r2: "আনলিমিটেড পিডিএফ রিপোর্ট",
    upgrade_r3: "ভেরিফাইড অর্গানাইজেশন ব্যাজ",
    btn_upgrade_pro: "স্মার্ট প্রো-তে আপগ্রেড করুন",

    // ✨ MASTER SETTINGS KEYS (BENGALI)
    settings_subtitle: "পরিচয়, ইউসেজ কাউন্টার এবং নিরাপদ অ্যাক্সেস পরিচালনা করুন।",
    official_identity: "অফিসিয়াল পরিচয়",
    name: "নাম",
    org_type: "প্রতিষ্ঠানের ধরন",
    official_phone: "অফিসিয়াল ফোন",
    official_email: "অফিসিয়াল ইমেইল",
    physical_address: "ঠিকানা",
    legal_info: "লিগ্যাল ও অতিরিক্ত তথ্য",
    reg_no: "রেজিস্ট্রেশন নং",
    tax_id: "ট্যাক্স আইডি (PAN/BIN/EIN)",
    mission_desc: "মিশন / বিবরণ",
    btn_save_settings: "সেটিংস সেভ করুন",
    admin_security: "অ্যাডমিন নিরাপত্তা",
    new_master_pass: "নতুন মাস্টার পাসওয়ার্ড",
    min_6_char: "কমপক্ষে ৬ অক্ষর",
    confirm_pass: "পাসওয়ার্ড নিশ্চিত করুন",
    retype_pass: "পাসওয়ার্ড পুনরায় লিখুন",
    btn_update_pass: "পাসওয়ার্ড আপডেট করুন",
    current_limits: "বর্তমান লিমিট",
    registered_members: "নিবন্ধিত সদস্য",
    pdfs_generated: "পিডিএফ জেনারেট হয়েছে",
    offer_dakshina: "দক্ষিণা প্রদান করুন (আপগ্রেড)",
    update_password: "পাসওয়ার্ড আপডেট",
    confirm_pass_update: "আপনি কি নিশ্চিত যে আপনি আপনার মাস্টার পাসওয়ার্ড পরিবর্তন করতে চান?",
    pass_updated_success: "পাসওয়ার্ড সফলভাবে আপডেট হয়েছে!",
    err_no_auth: "কোনো সক্রিয় সেশন পাওয়া যায়নি। আবার লগইন করুন।",
    err_recent_login: "নিরাপত্তা টাইমআউট। পাসওয়ার্ড পরিবর্তন করতে লগআউট করে আবার লগইন করুন।",
    err_trx_req: "যোগাযোগের মাধ্যম এবং ট্রানজ্যাকশন আইডি আবশ্যক।",
    req_submitted: "রিকোয়েস্ট জমা হয়েছে!",
    dakshina_submitted_desc: "✅ আপনার ট্রানজ্যাকশন আইডি জমা হয়েছে। আমাদের টিম ২৪ ঘণ্টার মধ্যে এটি যাচাই করে আপনার SMART PRO চালু করবে।",
    understood: "বুঝেছি",
    copied_success: "মার্চেন্ট নম্বর কপি হয়েছে!",
    settings_saved: "সেটিংস সফলভাবে আপডেট হয়েছে!",
    err_pass_length: "পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে।",
    err_pass_match: "পাসওয়ার্ড মেলেনি।",

    quotes: [
      { text: "कर्मण्येवाधिकारस्ते मा फलेषु कदाचन।", meaning: "কর্মেই তোমার অধিকার, ফলে নয়।", source: "Bhagavad Gita 2.47" },
      { text: "उद्धरेदात्मनात्मानं नात्मानमवसादयेत्।", meaning: "নিজের মনের শক্তিতে নিজেকে উন্নীত করুন, নিজেকে অধঃপতিত করবেন নিম্নলিখিত করবেন না।", source: "Bhagavad Gita 6.5" },
      { text: "सत्यमेव जयते नानृतं", meaning: "সত্যেরই জয় হয়, মিথ্যার নয়।", source: "Mundaka Upanishad 3.1.6" },
      { text: "एकं सद्विप्रा बहुधा वदन्ति", meaning: "সত্য একটাই, জ্ঞানীরা তাকে নানা নামে ডাকেন।", source: "Rig Veda 1.164.46" }
    ],

    Mandir: { workspace: "মন্দির", nav_directory: "ভক্ত ডিরেক্টরি", nav_panjika: "উৎসব ও পঞ্জিকা", nav_prachar: "ধর্ম প্রচার", members: "ভক্তবৃন্দ", funds: "চাঁদা", nav_assets: "মন্দিরের সম্পদ", nav_inventory: "ভাণ্ডার ও স্টোর" },
    Goshala: { workspace: "গোশালা", nav_directory: "গো-সেবক ডিরেক্টরি", nav_panjika: "গোশালা ইভেন্ট", nav_prachar: "গোশালা বার্তা", members: "গো-সেবক", funds: "গো-সেবা নিধি", nav_assets: "গোমাতা ও নন্দী রেকর্ড", nav_inventory: "খাদ্য ও চিকিৎসা" },
    Sangha: { workspace: "সংঘ", nav_directory: "সংঘের সদস্য", nav_panjika: "অধিবেশন", nav_prachar: "সংঘ বার্তা", members: "সদস্য", funds: "সহযোগ", nav_assets: "সংঘের সম্পদ", nav_inventory: "স্টোর ম্যানেজমেন্ট" },
    Ashram: { workspace: "আশ্রম", nav_directory: "সাধক ডিরেক্টরি", nav_panjika: "আশ্রমের সময়সূচী", nav_prachar: "আশ্রম বার্তা", members: "সাধকবৃন্দ", funds: "আশ্রম তহবিল", nav_assets: "আশ্রমের সম্পদ", nav_inventory: "রান্নাঘর ও চিকিৎসা" },
    Gurukul: { workspace: "গুরকুল", nav_directory: "শিক্ষার্থী ডিরেক্টরি", nav_panjika: "একাডেমিক ক্যালেন্ডার", nav_prachar: "শিক্ষার্থী বার্তা", members: "শিক্ষার্থীবৃন্দ", funds: "গুরু দক্ষিণা", nav_assets: "ক্যাম্পাস সম্পদ", nav_inventory: "লাইব্রেরি ও সাপ্লাই" },
    Satsang: { workspace: "সৎসঙ্গ কেন্দ্র", nav_directory: "অনুসারী ডিরেক্টরি", nav_panjika: "সৎসঙ্গ সময়সূচী", nav_prachar: "সৎসঙ্গ বার্তা", members: "অনুসারীবৃন্দ", funds: "ভেন্ট/প্রণামী", nav_assets: "কেন্দ্রের সম্পদ", nav_inventory: "স্টোর ম্যানেজমেন্ট" },
    Yoga: { workspace: "যোগ কেন্দ্র", nav_directory: "সাধক ডিরেক্টরি", nav_panjika: "ক্লাস রুটিন", nav_prachar: "যোগ বার্তা", members: "সাধকবৃন্দ", funds: "অনুদান", nav_assets: "সরঞ্জাম রেকর্ড", nav_inventory: "ইনভেন্টরি" },
    Trust: { workspace: "সেবা ট্রাস্ট", nav_directory: "সেবাদার ডিরেক্টরি", nav_panjika: "কর্মসূচী", nav_prachar: "ট্রাস্ট বার্তা", members: "সেবাদার", funds: "সেবা নিধি", nav_assets: "ট্রাস্ট সম্পদ", nav_inventory: "রিলিফ ও মেডিকেল স্টোর" }
  },

  hi: {
    app_name: "सनातनी बंधन",
    portal_subtitle: "सार्वभौमिक सामुदायिक पोर्टल",
    workspace: "कार्यक्षेत्र",
    status: "स्थिति", 
    nav_home: "कमांड सेंटर",
    nav_directory: "सदस्य निर्देशिका",
    nav_guests: "अतिथि सीआरएम",
    nav_treasury: "खजाना और खाता",
    nav_prachar: "प्रसारण डेस्क",
    nav_panjika: "कैलेंडर और कार्यक्रम",
    nav_polls: "मतदान प्रणाली",
    nav_marketing: "सोशल असिस्टेंट",
    nav_settings: "सेटिंग्स",
    nav_assets: "संपत्ति और रिकॉर्ड",
    nav_inventory: "स्टोर और इन्वेंटरी",
    members: "सदस्य",
    funds: "निधि",

    // ✨ HINDI TRANSLATIONS FOR NEW NAVIGATION KEYS
    nav_group_core: "मुख्य कार्यक्षेत्र",
    nav_group_community: "समुदाय और सीआरएम",
    nav_group_finance: "वित्त और कार्यक्रम",
    nav_group_settings: "प्रसारण और सेटिंग्स",
    nav_group_logistics: "पूजा और रसद",
    nav_vivah: "विवाह बंधन वैवाहिक",
    nav_vanshavali: "वंशवली रजिस्ट्री",
    nav_shradh: "पितृ श्राद्ध डेस्क",
    community_feed: "दर्शन और फीड",
    my_ritual_diary: "मेरी अनुष्ठान डायरी",

    login_secure: "सुरक्षित लॉगिन",
    login_create: "कार्यक्षेत्र बनाएँ",
    login_admin: "व्यवस्थापक",
    login_devotee: "भक्त / सदस्य",
    login_email: "व्यवस्थापक ईमेल",
    login_pass: "मास्टर पासवर्ड",
    login_wid: "कार्यक्षेत्र आईडी या ईमेल",
    login_identity: "आपकी आईडी, फोन, या ईमेल",
    login_pin: "सुरक्षित पिन (PIN)",
    btn_access_portal: "सुरक्षित प्रवेश",
    login_forgot: "पासवर्ड / पिन भूल गए?",
    reg_warning_title: "रुकें! क्या आप एक सदस्य हैं?",
    reg_warning_desc_1: "यदि आपका ",
    reg_warning_desc_2: " पहले से ही इस ऐप का उपयोग करता है, तो नया कार्यक्षेत्र न बनाएं। लॉगिन करने के लिए अपने व्यवस्थापक से आईडी मांगें।",
    reg_step1: "चरण 1: संगठन की जानकारी",
    reg_org_type: "संगठन का प्रकार",
    reg_org_name: "नाम",
    reg_address: "पूरा पता (वैकल्पिक)",
    reg_desc: "संक्षिप्त विवरण (वैकल्पिक)",
    reg_step2: "चरण 2: व्यवस्थापक प्रोफ़ाइल",
    reg_your_name: "आपका नाम *",
    reg_your_phone: "आपका फोन *",
    reg_official_email: "आधिकारिक ईमेल *",
    btn_create_dynamic: "सुरक्षित {X} बनाएँ",
    head_admin: "मुख्य व्यवस्थापक",

    hero_badge: "हिंदू समुदायों के लिए अंतिम कमांड सेंटर",
    hero_title_1: "कागजी रजिस्टरों से",
    hero_title_2: "डिजिटल कार्यक्षेत्र तक।",
    hero_subtitle: "अपने आश्रम, संघ या मंदिर को एकजुट करें। रिकॉर्ड खोना और धन पर विवाद बंद करें। आजीवन प्रोफाइल प्रबंधित करें, सुरक्षित रूप से धन ट्रैक करें, और अलर्ट प्रसारित करें—सब कुछ एक सुरक्षित डैशबोर्ड से।",
    btn_create_free: "मुफ़्त खाता बनाएँ",
    btn_watch_demo: "सिस्टम डेमो देखें",
    btn_login: "लॉग इन",
    btn_establish: "कार्यक्षेत्र स्थापित करें",
    nav_features: "विशेषताएं",
    nav_pricing: "मूल्य निर्धारण",
    nav_security: "सुरक्षा",
    trust_banner: "वैश्विक सनातनी परिवार को सशक्त बनाना",
    features_title: "डिजिटल प्रबंधन के चार मुख्य स्तंभ",
    features_subtitle: "समिति के सदस्यों के लिए सबसे बड़ी समस्याओं का समाधान।",
    footer_privacy: "गोपनीयता नीति",
    footer_terms: "सेवा की शर्तें",
    footer_contact: "संपर्क करें",

    enterprise_badge: "एंटरप्राइज-ग्रेड इंफ्रास्ट्रक्चर",
    enterprise_title: "आधुनिक समुदायों के लिए अगली पीढ़ी की तकनीक",
    feat_apk_title: "एंड्रॉयड एपीके और ओटीए सिंक",
    feat_apk_desc: "कैपगो ओवर-द-एयर साइलेंट अपडेट के साथ नेटिव ऑफलाइन ऐप सपोर्ट।",
    feat_memo_title: "जीरो-कॉस्ट मेमो स्कैन",
    feat_memo_desc: "क्लाइंट-साइड डीप इमेज कंप्रेशन जो क्लाउड स्टोरेज और बैंडविड्थ बचाता है।",
    feat_qr_title: "स्मार्ट क्यूआर ऑटो-लॉगिन",
    feat_qr_desc: "सुरक्षित लॉगिन डीप लिंक के साथ जनरेटेड पीडीएफ क्रेडेंशियल।",
    feat_support_title: "सुरक्षित लाइव समर्थन",
    feat_support_desc: "एचएमएसी सिक्योर मोड आइडेंटिफिकेशन के साथ एंटरप्राइज टॉर्क.टू विजेट।",

    contact_title: "समर्थन और बिक्री",
    contact_wa: "सीधा व्हाट्सएप",
    contact_wa_desc: "हमारी कोर टीम से सीधे त्वरित सहायता प्राप्त करें।",
    contact_wa_btn: "व्हाट्सएप पर मैसेज करें",
    contact_name: "आपका पूरा नाम",
    contact_info: "ईमेल या फोन नंबर",
    contact_msg: "हम आपकी कैसे मदद कर सकते हैं?",
    contact_send: "संदेश भेजें",

    feat_1_title: "कागजी रजिस्टर खोना बंद करें",
    feat_1_pain: "क्या आपकी भौतिक रिकॉर्ड पुस्तकें फट रही हैं, खो रही हैं, या खोजने में घंटों लग रहे हैं?",
    feat_1_sol: "हजारों प्रोफाइल को डिजिटल रूप से प्रबंधित करें, गोत्र को ट्रैक करें, और हमारे एन्क्रिप्टेड CRM के साथ सेकंडों में संपर्क विवरण खोजें।",
    feat_2_title: "वित्तीय विवादों को समाप्त करें",
    feat_2_pain: "क्या एकत्रित धन के साथ विश्वास की समस्या या मैन्युअल गणना त्रुटियां हो रही हैं?",
    feat_2_sol: "100% वित्तीय पारदर्शिता प्राप्त करें। आजीवन योगदान को सुरक्षित रूप से ट्रैक करें और तत्काल PDF ऑडिट रिपोर्ट तैयार करें।",
    feat_3_title: "सभी को एक साथ संदेश भेजें",
    feat_3_pain: "किसी कार्यक्रम में आमंत्रित करने या बकाया याद दिलाने के लिए सैकड़ों सदस्यों को अलग-अलग कॉल करना थका देने वाला है।",
    feat_3_sol: "एक क्लिक के साथ अपने पूरे समुदाय तक पहुंचें। घटनाओं के लिए स्वचालित जन SMS या व्हाट्सएप अलर्ट भेजें।",
    feat_4_title: "समिति के विवादों को सुलझाएं",
    feat_4_pain: "क्या समिति के फैसले अंतहीन तर्क और सर्वसम्मति की कमी पैदा कर रहे हैं?",
    feat_4_sol: "सामुदायिक मतदान के लिए सुरक्षित, एन्क्रिप्टेड डिजिटल पोल लॉन्च करें। हमारी तकनीक निष्पक्ष निर्णय लेने की गारंटी देती है।",

    pricing_title: "सनातनियों के लिए पारदर्शी मूल्य निर्धारण",
    pricing_subtitle: "मुफ्त में शुरू करें। जब आपका समुदाय बढ़े तो अपग्रेड करें।",
    pricing_forever: "हमेशा के लिए",
    pricing_per_year: "/ वर्ष",
    btn_start_free: "मुफ़्त कार्यक्षेत्र शुरू करें",
    free_feat_1: "अधिकतम {X} सदस्य प्रोफाइल",
    free_feat_2: "सामान्य निधि ट्रैकिंग",
    free_feat_3: "अधिकतम {X} सक्रिय पोल",
    free_feat_4: "प्रति माह {X} PDF रिपोर्ट",

    signed_in_as: "लॉग इन किया है",
    my_profile: "मेरी प्रोफ़ाइल",
    secure_logout: "सुरक्षित लॉगआउट",
    notifications: "सूचनाएं",
    no_notifications: "कोई नई सूचना नहीं!",
    new_request: "नया एक्सेस अनुरोध",
    upcoming_event: "आगामी कार्यक्रम",
    active_poll: "सक्रिय मतदान",
    quick_guide_title: "कमांड सेंटर गाइड",

    req_identity_data: "आवश्यक पहचान डेटा",
    ext_details: "विस्तृत जानकारी (वैकल्पिक)",
    nid: "राष्ट्रीय पहचान पत्र (NID)",
    father_name: "पिता का नाम",
    mother_name: "माता का नाम",
    full_address: "पूरा पता",
    cultural_desig: "सांस्कृतिक पदनाम",
    sys_role: "सिस्टम एक्सेस रोल",
    prov_profile: "प्रोफ़ाइल बनाएँ",
    seva_index: "सेवा सूचकांक",
    seva_desc: "आपकी वर्तमान रैंक है",
    digital_qr: "डिजिटल क्यूआर (QR) पहचान",
    qr_desc: "डिवाइस प्रमाणीकरण के लिए सुरक्षित पीडीएफ आईडी कार्ड जेनरेट करें या लाइव ऑटो-लॉगिन क्यूआर कोड देखें।",
    view_qr: "लाइव क्यूआर देखें",
    hide_qr: "क्यूआर छिपाएं",
    download_pdf_card: "पीडीएफ कार्ड डाउनलोड करें",
    scan_auto_login: "लॉगिन करने के लिए स्कैन करें",
    recent_trans: "हाल का लेनदेन",
    pdf_report: "पीडीएफ रिपोर्ट",
    msg_whatsapp: "व्हाट्सएप पर संदेश भेजें",
    admin_controls: "व्यवस्थापक नियंत्रण",
    reset_pin: "सुरक्षित पिन रीसेट करें",
    demote_member: "सदस्य के रूप में डिमोट करें",
    promote_manager: "प्रबंधक के रूप में प्रमोट करें",
    delete_record: "रिकॉर्ड स्थायी रूप से मिटाएं",
    identity_tab: "पहचान",
    activity_tab: "गतिविधि",
    security_tab: "सुरक्षा",
    gate_pass: "गेट पास",
    vedic_hub: "वैदिक हब",
    contact_geo: "संपर्क और भूगोल",
    blood_group: "रक्त समूह",
    country: "देश",
    gotra_lineage: "गोत्र / वंश",
    not_provided: "उपलब्ध नहीं है",

    // ✨ VIVAH & GLOBAL PUROHIT WIDGET KEYS
    vivah_title: "विवाह बंधन मैट्रिमोनियल",
    vivah_subtitle: "गोत्र और सनातन मूल्यों पर आधारित पारिवारिक मैचमेकिंग।",
    create_profile: "प्रोफ़ाइल बनाएँ",
    global_purohit_registry: "ग्लोबल पुरोहित निर्देशिका",
    apply_global_purohit: "ग्लोबल पुरोहित के रूप में आवेदन करें",
    apply_purohit_desc: "वैश्विक बुकिंग के लिए प्रोफ़ाइल सबमिट करें।",
    btn_submit_kyc: "KYC जमा करें",
    application_submitted: "आवेदन सत्यापन के लिए प्रस्तुत किया गया है!",
    global_scholar: "ग्लोबल स्कॉलर",
    account_recovery_qr: "खाता पुनर्प्राप्ति QR",
    qr_recovery_desc: "यदि आप अपना पिन भूल जाते हैं तो स्वचालित रूप से लॉग इन करने के लिए इसे डाउनलोड या स्कैन करें।",
    qr_warning: "चेतावनी: इस QR कोड में आपका सुरक्षित पिन है। इसे गेट पर न दिखाएं। इसके बजाय 'गेट पास' का उपयोग करें।",

    // ✨ GLOBAL PUROHIT KYC MODAL KEYS (HINDI)
    kyc_form_title: "ग्लोबल स्कॉलर केवाईसी (KYC) आवेदन",
    kyc_form_subtitle: "सत्यापित वैश्विक निर्देशिका में शामिल होने के लिए अपना विवरण जमा करें।",
    kyc_specialization: "प्राथमिक विशेषज्ञता",
    kyc_specialization_ph: "उदा. विवाह संस्कार, वास्तु शांति, ज्योतिष",
    kyc_experience: "अनुभव के वर्ष",
    kyc_lineage: "गोत्र और वैदिक वंश",
    kyc_lineage_ph: "उदा. कश्यप गोत्र, ऋग्वेद",
    kyc_location: "वर्तमान शहर / मंदिर",
    kyc_location_ph: "उदा. काशी विश्वनाथ, वाराणसी",
    kyc_document: "सत्यापन दस्तावेज (आईडी/प्रमाणपत्र)",
    btn_submit_application: "केवाईसी आवेदन जमा करें",

    // ✨ GUEST MANAGER KEYS (HINDI)
    guest_crm_title: "अतिथि संबंध और इवेंट चेक-इन",
    guest_crm_subtitle: "नए आगंतुकों को सदस्य बनाएं, VIP निमंत्रण प्रबंधित करें, और गेट पर उपस्थिति दर्ज करें।",
    growth_pipeline: "ग्रोथ पाइपलाइन", 
    event_roster: "इवेंट रोस्टर और गेट",
    add_new_guest: "नया अतिथि जोड़ें",
    search_guest: "नाम, फोन, या व्यवस्थापक नोट से खोजें...",
    gate_checkin_mode: "गेट चेक-इन मोड",
    select_event: "एक इवेंट चुनें",
    switch_event: "सक्रिय इवेंट बदलें",
    door_roster: "उपस्थिति रोस्टर (डोर)",
    checked_in: "चेक-इन किया गया:",
    no_events_found: "पंचांग में कोई आगामी कार्यक्रम नहीं मिला।",
    convert_member: "सदस्य बनाएं",
    active_member: "सक्रिय सदस्य",
    gate_checkin: "गेट चेक-इन",
    register_guest: "नया अतिथि पंजीकृत करें",
    classification: "वर्गीकरण",
    general_guest: "सामान्य अतिथि",
    vip_dignitary: "वीआईपी अतिथि",
    walk_in_donor: "वॉक-इन दाता",
    volunteer_prospect: "स्वयंसेवक संभावना",
    admin_note: "व्यवस्थापक संदर्भ नोट",
    save_pipeline: "पाइपलाइन में सहेजें",
    promote_devotee: "सदस्य के रूप में प्रमोट करें",
    delete_guest: "अतिथि रिकॉर्ड हटाएं",

    // ✨ DEVOTEE GRID: CHANDA, FILTERS, & CSV (HINDI)
    filters: "फ़िल्टर",
    filter_all: "सभी गतिविधियाँ",
    filter_income: "केवल आय",
    filter_expense: "केवल व्यय",
    amount_bdt: "राशि (৳) *",
    payment_method: "भुगतान विधि",
    note_optional: "विवरण (वैकल्पिक)",
    handled_by: "संग्रहकर्ता *",
    search_name: "नाम लिखकर खोजें...",
    btn_generate_receipt: "आधिकारिक पीडीएफ रसीद जनरेट करें",
    no_matching_activities: "कोई रिकॉर्ड नहीं मिला।",
    bulk_csv_importer: "बल्क CSV आयातक",
    csv_subtitle: "कागजी रजिस्टरों को तुरंत डिजिटल करें।",
    download_template: "टेम्पलेट डाउनलोड करें",
    format_data: "डेटा को प्रारूपित करें",
    upload_file: "फ़ाइल अपलोड करें",
    data_validated: "डेटा सत्यापित",
    records: "प्रोफाइल",
    btn_cancel: "रद्द करें",
    btn_import: "आयात (Import)",
    guide_devotee_step1_title: "1. प्रोफाइल बनाएं",
    guide_devotee_step1_desc: "अपने डिजिटल कार्यक्षेत्र में सदस्यों को सुरक्षित रूप से जोड़ें। ऑटो-लॉगिन क्यूआर कोड के साथ पीडीएफ आईडी कार्ड जनरेट करें।",
    guide_devotee_step2_title: "2. योगदान दर्ज करें",
    guide_devotee_step2_desc: "सीधे सदस्य की प्रोफ़ाइल पर दान लॉग करें और तुरंत पीडीएफ रसीदें डाउनलोड और साझा करें।",
    guide_devotee_step3_title: "3. व्यवस्थापक नियंत्रण",
    guide_devotee_step3_desc: "सुरक्षा टैब से भूमिकाएं (प्रबंधक/व्यवस्थापक) असाइन करें, सुरक्षित पिन रीसेट करें, या पहचान विवरण अपडेट करें।",

    // ✨ TREASURY & LEDGER KEYS (HINDI)
    err_only_images: "केवल चित्र अनुमत हैं।",
    error: "त्रुटि",
    success: "सफल",
    err_unauthorized: "अनाधिकृत।",
    err_amount_required: "राशि आवश्यक है।",
    err_select_member: "एक सदस्य का चयन करें।",
    err_guest_name_req: "अतिथि का नाम आवश्यक है।",
    recorded_success: "सफलतापूर्वक दर्ज किया गया!",
    err_all_fields_req: "सभी फ़ील्ड आवश्यक हैं।",
    no_memo: "कोई मेमो नहीं",
    edit_cost: "लागत संपादित करें",
    current: "वर्तमान",
    enter_new_amt: "नई राशि दर्ज करें",
    record_updated: "सफलतापूर्वक अपडेट किया गया।",
    pdf_engine_loading: "पीडीएफ इंजन लोड हो रहा है...",
    no_data_export: "निर्यात करने के लिए कोई डेटा नहीं है।",
    pdf_limit_reached: "सीमा पार हो गई।",
    date: "तारीख",
    donor_name: "नाम",
    amount: "राशि",
    note: "विवरण",
    collected_by: "संग्रहकर्ता",
    event: "कार्यक्रम",
    item: "आइटम",
    memo_no: "मेमो नंबर",
    logged_by: "दर्जकर्ता",
    unknown_donor: "अज्ञात",
    unknown_event: "अज्ञात",
    treasury_title: "ट्रेजरी लेजर",
    treasury_subtitle: "वित्तीय ट्रैकिंग",
    quick_guide: "क्विक गाइड",
    sort_newest: "सबसे नया",
    sort_oldest: "सबसे पुराना",
    sort_high: "उच्चतम राशि",
    sort_low: "न्यूनतम राशि",
    export_csv: "CSV",
    export_pdf: "PDF",
    how_to_use: "ट्रेजरी का उपयोग कैसे करें",
    guide_step1_title: "1. लेनदेन दर्ज करें",
    guide_step1_desc: "धन या व्यय दर्ज करने के लिए लाल/हरे + बटन का उपयोग करें। आप दाताओं के लिए तुरंत पीडीएफ रसीद जनरेट कर सकते हैं।",
    guide_step2_title: "2. मुफ्त में मेमो संलग्न करें",
    guide_step2_desc: "खर्च दर्ज करते समय, भौतिक मेमो की तस्वीर लेने के लिए कैमरा आइकन पर टैप करें। यह शून्य डेटाबेस लागत पर सुरक्षित रूप से सहेजता है।",
    guide_step3_title: "3. ट्रैक और निर्यात",
    guide_step3_desc: "तारीख, नाम, या राशि के अनुसार फ़िल्टर करें। फिर आधिकारिक ऑडिट रिपोर्ट के लिए Export PDF पर क्लिक करें।",
    tab_chanda: "चंदा/आय",
    tab_expenses: "खर्च",
    total_amount: "कुल राशि",
    filtered: "फ़िल्टर्ड",
    btn_record_chanda: "आय दर्ज करें",
    btn_record_expense: "खर्च दर्ज करें",
    search_donors: "दाताओं को खोजें...",
    search_events: "इवेंट खोजें...",
    contributions: "योगदान",
    seva_items: "आइटम",
    general_donation: "सामान्य दान",
    memo: "मेमो",
    edit_history: "संपादित इतिहास",
    view_memo_photo: "मेमो देखें",
    download_receipt: "रसीद डाउनलोड करें",
    no_data_found: "कोई डेटा नहीं मिला",
    adjust_filters: "परिणाम देखने के लिए फ़िल्टर बदलें",
    page: "पृष्ठ", 
    registered_devotee: "सदस्य",
    guest_donor: "अतिथि",
    search_directory: "निर्देशिका खोजें",
    type_to_search: "खोजने के लिए टाइप करें...",
    guest_name: "अतिथि का नाम",
    guest_phone: "अतिथि फोन",
    optional: "वैकल्पिक",
    cash: "नकद",
    bank_transfer: "बैंक ट्रांसफर",
    mobile_banking: "मोबाइल बैंकिंग",
    btn_confirm_chanda: "पुष्टि करें",
    btn_confirm_expense: "पुष्टि करें",
    event_name: "कार्यक्रम का नाम",
    item_purchased: "आइटम",
    photo_attached: "फोटो संलग्न",
    attach_memo_photo: "मेमो फोटो संलग्न करें",
    change_photo: "बदलें",
    take_photo_desc: "भौतिक रसीद की तस्वीर लेने के लिए क्लिक करें।",

    // ✨ POOJA & SEVA BOOKING KEYS (HINDI)
    nav_pooja: "पूजा और सेवा डेस्क",
    pooja_desk_desc: "अनुष्ठान आरक्षण प्रबंधित करें और मंदिर के राजस्व को सिंक करें।",
    active_bookings: "सक्रिय बुकिंग",
    pooja_catalog: "पूजा कैटलॉग",
    book_pooja: "नई पूजा बुक करें",
    schedule_pooja: "पूजा और सेवा निर्धारित करें",
    pooja_satyanarayan: "सत्यनारायण कथा और पूजा",
    pooja_rudrabhishek: "रुद्राभिषेक सेवा",
    pooja_namakaran: "नामकरण संस्कार",
    pooja_grihapravesh: "गृह प्रवेश पूजा",
    pooja_archana: "दैनिक अर्चना / पुष्पांजलि",
    search_records: "भक्त, पूजा, या गोत्र से खोजें...",
    devotee_name: "यजमान / भक्त",
    devotee_full_name: "भक्त का पूरा नाम",
    gotra: "गोत्र",
    nakshatra: "नक्षत्र",
    assigned_purohit: "नियुक्त पुरोहित",
    pooja_type: "अनुष्ठान / सेवा चुनें",
    yajamana_name: "यजमान का नाम",
    essential: "आवश्यक",
    booking_date: "बुकिंग की तारीख",
    dakshina_amount: "दक्षिणा राशि",
    btn_confirm_booking: "बुकिंग की पुष्टि करें और ट्रेजरी सिंक करें",
    archived: "पुरालेख",
    mark_completed: "पूरा करें",
    cancel: "रद्द करें",
    book_now: "बुक करें",

    // ✨ PROFILE & NOTIFICATIONS ENGINE KEYS (HINDI)
    updates: "अपडेट",
    activity_center: "गतिविधि केंद्र",
    pending: "लंबित",
    no_activities: "कोई गतिविधि नहीं मिली।",
    req_approval: "मंजूरी का अनुरोध:",
    btn_approve: "मंजूर करें",
    btn_reject: "अस्वीकार करें",
    performed_action: "कार्रवाई की:",
    operating_currency: "संचालन मुद्रा",
    tap_to_edit: "संपादित करने के लिए टैप करें",
    full_name: "पूरा नाम",
    phone_number: "फ़ोन नंबर",
    email: "ईमेल",
    personal_transactions: "व्यक्तिगत लेनदेन",
    security_controls: "सुरक्षा नियंत्रण",
    btn_save: "सहेजें",
    events_attended: "इवेंट में भाग लिया",
    lifetime_donated: "कुल दान",

    upgrade_title: "स्केल करने के लिए तैयार हैं?",
    upgrade_r1: "असीमित सदस्य प्रोफाइल",
    upgrade_r2: "अनंत मास्टर पीडीएफ रिपोर्ट",
    upgrade_r3: "सत्यापित संगठन बैज",
    btn_upgrade_pro: "स्मार्ट प्रो में अपग्रेड करें",

    // ✨ MASTER SETTINGS KEYS (HINDI)
    settings_subtitle: "पहचान, उपयोग काउंटर और सुरक्षित पहुंच प्रबंधित करें।",
    official_identity: "आधिकारिक पहचान",
    name: "नाम",
    org_type: "संगठन का प्रकार",
    official_phone: "आधिकारिक फोन",
    official_email: "आधिकारिक ईमेल",
    physical_address: "पता",
    legal_info: "कानूनी और अतिरिक्त जानकारी",
    reg_no: "पंजीकरण संख्या",
    tax_id: "टैक्स आईडी (PAN/BIN/EIN)",
    mission_desc: "मिशन / विवरण",
    btn_save_settings: "सेटिंग्स सहेजें",
    admin_security: "व्यवस्थापक सुरक्षा",
    new_master_pass: "नया मास्टर पासवर्ड",
    min_6_char: "कम से कम 6 अक्षर",
    confirm_pass: "पासवर्ड की पुष्टि करें",
    retype_pass: "पासवर्ड फिर से लिखें",
    btn_update_pass: "पासवर्ड अपडेट करें",
    current_limits: "वर्तमान सीमाएँ",
    registered_members: "पंजीकृत सदस्य",
    pdfs_generated: "पीडीएफ जनरेट किए गए",
    offer_dakshina: "दक्षिणा दें (अपग्रेड)",
    update_password: "पासवर्ड अपडेट",
    confirm_pass_update: "क्या आप निश्चित रूप से अपना मास्टर पासवर्ड बदलना चाहते हैं?",
    pass_updated_success: "पासवर्ड सफलतापूर्वक अपडेट किया गया!",
    err_no_auth: "कोई सक्रिय सत्र नहीं मिला। कृपया फिर से लॉगिन करें।",
    err_recent_login: "सुरक्षा टाइमआउट। पासवर्ड बदलने के लिए लॉगआउट करें और फिर से लॉगिन करें।",
    err_trx_req: "संपर्क और लेनदेन आईडी आवश्यक हैं।",
    req_submitted: "अनुरोध जमा किया गया!",
    dakshina_submitted_desc: "✅ आपकी लेनदेन आईडी जमा कर दी गई है। हमारी टीम 24 घंटों के भीतर इसे सत्यापित करेगी और आपका SMART PRO सक्रिय करेगी।",
    understood: "समझ गया",
    copied_success: "मर्चेंट नंबर कॉपी किया गया!",
    settings_saved: "सेटिंग्स सफलतापूर्वक अपडेट की गईं!",
    err_pass_length: "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।",
    err_pass_match: "पासवर्ड मेल नहीं खाते।",

    quotes: [
      { text: "कर्मण्येवाधिकारस्ते मा फलेषु कदाचन।", meaning: "कर्म पर ही तुम्हारा अधिकार है, कर्म के फलों में कभी नहीं।", source: "Bhagavad Gita 2.47" },
      { text: "उद्धरेदात्मनात्मानं नात्मानमवसादयेत्।", meaning: "अपने मन की शक्ति से स्वयं का उद्धार करें, स्वयं को पतन की ओर न ले जाएं।", source: "Bhagavad Gita 6.5" },
      { text: "सत्यमेव जयते नानृतं", meaning: "सत्य की ही विजय होती है, झूठ की नहीं।", source: "Mundaka Upanishad 3.1.6" },
      { text: "एकं सद्विप्रा बहुधा वदन्ति", meaning: "सत्य एक है, ज्ञानी उसे कई नामों से पुकारते हैं।", source: "Rig Veda 1.164.46" }
    ],

    Mandir: { workspace: "मंदिर", nav_directory: "भक्त निर्देशिका", nav_panjika: "उत्सव और पंचांग", nav_prachar: "धर्म प्रचार", members: "भक्तजन", funds: "चंदा / दान", nav_assets: "मंदिर की संपत्ति", nav_inventory: "भंडारा और स्टोर" },
    Goshala: { workspace: "गौशाला", nav_directory: "गौ-सेवक निर्देशिका", nav_panjika: "गौशाला कार्यक्रम", nav_prachar: "गौशाला प्रसारण", members: "गौ-सेवक", funds: "गौ-सेवा निधि", nav_assets: "गौमाता और नंदी रिकॉर्ड", nav_inventory: "चारा और चिकित्सा" },
    Sangha: { workspace: "संघ", nav_directory: "संघ के सदस्य", nav_panjika: "अधिवेशन", nav_prachar: "संघ प्रसारण", members: "सदस्य", funds: "सहयोग", nav_assets: "संघ की संपत्ति", nav_inventory: "स्टोर प्रबंधन" },
    Ashram: { workspace: "आश्रम", nav_directory: "साधक निर्देशिका", nav_panjika: "आश्रम अनुसूची", nav_prachar: "आश्रम प्रसारण", members: "साधक", funds: "आश्रम निधि", nav_assets: "आश्रम की संपत्ति", nav_inventory: "रसोई और चिकित्सा" }, 
    Gurukul: { workspace: "गुरुकुल", nav_directory: "विद्यार्थी निर्देशिका", nav_panjika: "शैक्षणिक पंचांग", nav_prachar: "विद्यार्थी सूचना", members: "विद्यार्थी", funds: "गुरु दक्षिणा", nav_assets: "परिसर की संपत्ति", nav_inventory: "पुस्तकालय और आपूर्ति" },
    Satsang: { workspace: "सत्संग केंद्र", nav_directory: "अनुयायी निर्देशिका", nav_panjika: "सत्संग अनुसूची", nav_prachar: "सत्संग प्रसारण", members: "अनुयायी", funds: "भेंट", nav_assets: "केंद्र की संपत्ति", nav_inventory: "स्टोर प्रबंधन" }, 
    Yoga: { workspace: "योग केंद्र", nav_directory: "साधक निर्देशिका", nav_panjika: "कक्षा अनुसूची", nav_prachar: "योग प्रसारण", members: "साधक", funds: "योग निधि", nav_assets: "उपकरण रिकॉर्ड", nav_inventory: "इन्वेंटरी" },
    Trust: { workspace: "सेवा ट्रस्ट", nav_directory: "सेवादार निर्देशिका", nav_panjika: "गतिविधि पंचांग", nav_prachar: "ट्रस्ट प्रसारण", members: "सेवादार", funds: "सेवा निधि", nav_assets: "ट्रस्ट की संपत्ति", nav_inventory: "राहत और मेडिकल स्टोर" } 
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('sanatani_lang') || 'en');
  const [workspaceType, setWorkspaceType] = useState('General'); 

  useEffect(() => {
    localStorage.setItem('sanatani_lang', language);
  }, [language]);

  const t = (key) => {
    // 🛡️ Added safety fallback to prevent runtime crashes if language state is corrupted
    let langDict = translations[language];
    if (!langDict) langDict = translations['en'];

    // 1. Workspace specific override (e.g. Mandir, Goshala)
    if (langDict[workspaceType] && langDict[workspaceType][key]) {
      return langDict[workspaceType][key];
    }
    // 2. Current language root
    if (langDict[key]) {
      return langDict[key];
    }
    // 3. Fallback to English root
    return translations['en'][key] || key;
  };

  const getArray = (key) => {
    let langDict = translations[language];
    if (!langDict) langDict = translations['en'];
    return langDict[key] || translations['en'][key] || [];
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, workspaceType, setWorkspaceType, t, getArray }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
